### ISSUE TITLE
iOS Controls

### ISSUE THREAD

**Issue by jossmac** [touchstonejs/touchstonejs#25]
A good place to start http://iosdesign.ivomynttinen.com/

Done:
- [x] Navigation bar (currently Headerbar)
- [x] Lists
- [x] Grouped Lists
- [x] Icon with list item
- [x] Chevron with list item
- [x] List item with subtitle

Implemented, but needs work:
- [ ] Tab Bar (currently Footerbar)
- [ ] Search Bar
- [ ] Segment Controls (currently Toggle)

Yet to be implemented:
- [ ] List item with value
- [ ] Switch
- [ ] Stepper
- [ ] Toolbar
